import h5py as h5p
from os import chdir
import sys
import MDSplus as mds

## Variable definitions
tubenum = 48
change2txt=int(sys.argv[1])
thtck = int(sys.argv[2])
SHOT = int(sys.argv[3])

chdir('/Users/unterbee/Desktop/Project_HELIOS/APS_2011')

#Load in the calibration files
file=h5p.File('InherNums_2011.h5')
InherNum=file['InherNum'].value
FilterNams=file['FilterNams'].value
file.close()

###---For thin connections
if thtck == 0:
    #MDScon = mds.Connection('localhost')
    MDScon = mds.Connection('134.94.245.16')
    MDScon.openTree('helios',SHOT)

###---For thick connections
if thtck == 1:
    TreeObj = mds.Tree('helios',SHOT)

for j in range(1,tubenum+1):
    if j < 10:
        TUBEstr='TUBE0'+str(j)
    else:
        TUBEstr='TUBE'+str(j)

    inherNode = TreeObj.getNode(':'+TUBEstr).getNode('FS_COEFF_I_N')
    filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILT_ID')
    relconstNode = TreeObj.getNode(':'+TUBEstr).getNode('REL_CONST')

    if j==1:
        putdat0 = mds.Float32(InherNum[50])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILT_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILT_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[50])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==2:
    	putdat0 = mds.Float32(InherNum[36])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[36])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==3:
    	putdat0 = mds.Float32(InherNum[24])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[24])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==4:
    	putdat0 = mds.Float32(InherNum[2])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[2])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==5:
    	putdat0 = mds.Float32(InherNum[39])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[39])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==6:
    	putdat0 = mds.Float32(InherNum[25])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[25])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==7:
    	putdat0 = mds.Float32(InherNum[13])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[13])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==8:
    	putdat0 = mds.Float32(InherNum[5])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[5])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==9:
    	putdat0 = mds.Float32(InherNum[40])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[40])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==10:
    	putdat0 = mds.Float32(InherNum[26])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[26])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==11:
    	putdat0 = mds.Float32(InherNum[15])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[15])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==12:
    	putdat0 = mds.Float32(InherNum[7])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[7])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==13:
    	putdat0 = mds.Float32(InherNum[11])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[11])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==14:
    	putdat0 = mds.Float32(InherNum[19])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[19])
        filteridNode.putData(putdat1)
        relconstNode.putData(putdat2)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==15:
    	putdat0 = mds.Float32(InherNum[31])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[31])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==16:
    	putdat0 = mds.Float32(InherNum[48])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[48])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==17:
    	putdat0 = mds.Float32(InherNum[8])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[8])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==18:
    	putdat0 = mds.Float32(InherNum[14])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[14])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==19:
    	putdat0 = mds.Float32(InherNum[29])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[29])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==20:
    	putdat0 = mds.Float32(InherNum[44])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[44])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==21:
    	putdat0 = mds.Float32(InherNum[10])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[10])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==22:
    	putdat0 = mds.Float32(InherNum[17])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[17])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==23:
    	putdat0 = mds.Float32(InherNum[30])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[30])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==24:
    	putdat0 = mds.Float32(InherNum[43])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[43])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==25:
    	putdat0 = mds.Float32(InherNum[37])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[37])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==26:
    	putdat0 = mds.Float32(InherNum[27])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[27])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==27:
    	putdat0 = mds.Float32(InherNum[22])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[22])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==28:
    	putdat0 = mds.Float32(InherNum[3])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[3])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==29:
    	putdat0 = mds.Float32(InherNum[49])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[49])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==30:
    	putdat0 = mds.Float32(InherNum[35])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[35])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==31:
    	putdat0 = mds.Float32(InherNum[23])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[23])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==32:
    	putdat0 = mds.Float32(InherNum[4])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[4])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==33:
    	putdat0 = mds.Float32(InherNum[45])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[45])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==34:
    	putdat0 = mds.Float32(InherNum[28])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[28])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==35:
    	putdat0 = mds.Float32(InherNum[18])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[18])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==36:
    	putdat0 = mds.Float32(InherNum[0])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[0])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==37:
    	putdat0 = mds.Float32(InherNum[6])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[6])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==38:
    	putdat0 = mds.Float32(InherNum[12])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[12])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==39:
    	putdat0 = mds.Float32(InherNum[32])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[32])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==40:
    	putdat0 = mds.Float32(InherNum[46])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[46])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==41:
    	putdat0 = mds.Float32(InherNum[1])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[1])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==42:
    	putdat0 = mds.Float32(InherNum[20])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[20])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==43:
    	putdat0 = mds.Float32(InherNum[33])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[33])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==44:
    	putdat0 = mds.Float32(InherNum[41])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[41])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==45:
    	putdat0 = mds.Float32(InherNum[9])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[9])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==46:
    	putdat0 = mds.Float32(InherNum[16])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[16])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==47:
    	putdat0 = mds.Float32(InherNum[34])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[34])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)
    if j==48:
    	putdat0 = mds.Float32(InherNum[42])
        inherNode.putData(putdat0)
        if change2txt == 1:
        	TreeObj.deleteNode('.'+TUBEstr+':FILTER_ID')
        	TreeObj.addNode('.'+TUBEstr+':FILTER_ID','TEXT')
        	TreeObj.write()
        	filteridNode = TreeObj.getNode(':'+TUBEstr).getNode('FILTER_ID')
        putdat1 = mds.String(FilterNams[42])
        filteridNode.putData(putdat1)
        putdat2 = mds.Float32(1.0)
        relconstNode.putData(putdat2)